// src/components/AddItem.vue
<script setup lang="ts">
import { reactive, ref, useTemplateRef } from 'vue';

const localStorage = window.localStorage;
const page = ref(localStorage.getItem("routerState"));

const modal = useTemplateRef('contextModal');

document.addEventListener('click', (e) => {
  if (modal && modal.value?.open && !e.composedPath().includes(modal.value)) {
    modal.value?.close();
  }
}, { capture: true })

const formValues = ref({
  name: '',
  amount: '',
});

const reset = () => {
  formValues.value.name = '';
  formValues.value.amount = '';
}

const onSubmit = async () => {
  console.log(formValues.value);
}
</script>

<template>
  <div>
    <div class="buttonWrapperClosed" @click="() => {
      page = localStorage.getItem('routerState');
      modal?.showModal();
    }">
      <div style="position: relative;">
        <v-icon name="md-playlistadd" scale="3" fill="#232323" />
        <v-icon name="md-playlistadd" scale="3" fill="#23232340" style="position: absolute; left: 2px; top: 2px;" />
      </div>
    </div>

    <dialog class="buttonWrapperOpen" ref="contextModal">
      <div
        style="display: flex; flex-direction: row; justify-content: space-between; padding-top: 5px; padding-bottom: 5px;">
        <p style="font-size: 16px; margin: 5px 0 0 5px; padding: 0;"
          v-text="page && page != '/' ? 'Add list' : 'Add item'" />
        <div @click="modal?.close()">
          <v-icon name="bi-chevron-down" scale="1.5" />
        </div>
      </div>
      <div class="openForm">
        <div class="formWrapper">
          <label class="formText"> Name: </label>
          <input type="text" class="formInput" />
        </div>
        <div class="formWrapper" v-if="page !== 'lists'">
          <label class="formText"> Amount: </label>
          <input type="text" class="formInput" style="width: 50px;" />
        </div>
        <div @click="onSubmit" class="button">
          <p style="font-size: 14px;">Add to list</p>
        </div>
      </div>
    </dialog>
  </div>
</template>

<style lang="scss" scoped>
.buttonWrapperClosed {
  position: absolute;
  bottom: 10px;
  right: 10px;
  background-color: #FFA500;
  padding: 10px;
  border-radius: 100px;
  border: solid 4px rgba(0, 0, 0, 0.3);
}

.buttonWrapperOpen {
  align-self: flex-end;
  margin-bottom: 5px;
  justify-self: center;
  background-color: #FFA500;
  border-radius: 10px;
  height: 200px;
  width: 100%;
}

.openForm {
  background-color: #404040;
  width: 100%;
  height: 173px;
  border-bottom-right-radius: 10px;
  border-bottom-left-radius: 10px;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 15px;
  padding-top: 20px;
}

.button {
  background-color: #FFA500;
  width: 100px;
  height: 35px;
  border-radius: 10px;
  display: flex;
  justify-content: center;
  align-items: center;
  position: absolute;
  bottom: 10px;
}

.formWrapper {
  display: flex;
  gap: 15px;
  flex-direction: row;
  height: 35px;
  align-items: center;
  align-self: flex-start;
  margin-left: 5px;
}

.formInput {
  height: 35px;
  width: 250px;
  text-align: left;
  padding-left: 5px;
  padding-right: 5px;
  color: #FEFEFE;
  background-color: #505050;
  border-radius: 5px;
}

.formText {
  color: #FEFEFE;
  width: 50px;
}

.errorText {
  position: absolute;
  top: 3px;
  color: #FF3333;
}

dialog {
  margin: 0;
  padding: 0;
}

dialog::backdrop {
  pointer-events: none;
  display: none;
}
</style>

// components/AddItem.tsx
import { addItemOpenAtom, selectedListAtom, selectedPageAtom, settingsAtom } from '@/atoms';
import { Entypo, MaterialIcons } from '@expo/vector-icons';
import { useSQLiteContext } from 'expo-sqlite';
import { useAtom } from 'jotai';
import { useRef } from 'react';
import { Controller, useForm } from 'react-hook-form';
import { StyleSheet, TouchableOpacity, View, Text, TextInput, Keyboard } from 'react-native';

interface IForm {
  name: string
  amount: string
}

export const AddItem = () => {
  const db = useSQLiteContext();
  const [settings] = useAtom(settingsAtom);
  const [pickedList, setPickedList] = useAtom(selectedListAtom);
  const [page] = useAtom(selectedPageAtom);
  const [open, setOpen] = useAtom(addItemOpenAtom);
  const { control, handleSubmit, reset, formState: { errors } } = useForm<IForm>({
    defaultValues: {
      name: '',
      amount: '',
    },
  });
  const amountRef: any = useRef();

  const styles = StyleSheet.create({
    buttonWrapperClosed: {
      position: 'absolute',
      bottom: 10,
      right: 10,
      backgroundColor: '#FFA500',
      padding: 10,
      borderRadius: 100,
      borderStyle: 'solid',
      borderWidth: 4,
      borderColor: '#FFA50080',
    },
    buttonWrapperOpen: {
      position: 'absolute',
      bottom: 10,
      right: 10,
      borderRadius: 10,
      backgroundColor: '#FFA500',
      height: 200,
      width: '95%',
    },
    openForm: {
      backgroundColor: settings?.theme ? settings?.theme[settings?.chosenTheme].modalBackground : '#404040',
      width: '100%',
      height: 173,
      borderBottomRightRadius: 10,
      borderBottomLeftRadius: 10,
      display: 'flex',
      alignItems: 'center',
      gap: 10,
      paddingTop: 20,
    },
    button: {
      backgroundColor: settings?.theme ? settings?.theme[settings?.chosenTheme].modalTrim : '#FFA500',
      width: 100,
      height: 35,
      borderRadius: 10,
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      position: 'absolute',
      bottom: 10,
    },
    formWrapper: {
      display: 'flex',
      flexDirection: 'row',
      height: 35,
      alignItems: 'center',
      alignSelf: 'flex-start',
      left: 5,
    },
    formInput: {
      height: 35,
      width: 250,
      textAlign: 'left',
      paddingLeft: 5,
      paddingRight: 5,
      color: '#fefefe',
      backgroundColor: '#505050',
      borderRadius: 5,
    },
    formText: {
      color: '#FEFEFE',
      width: 50,
    },
    errorText: {
      position: 'absolute',
      top: 3,
      color: '#FF3333',
    },
  });

  const onSubmit = handleSubmit(async (data) => {
    if (page === 'lists') {
      console.log(data.name);
      Keyboard.dismiss();
      reset();
    }
    else {
      console.log(data);
      Keyboard.dismiss();
      reset();
    }
  });

  return (
    <TouchableOpacity
      activeOpacity={0.8}
      style={open ? styles.buttonWrapperOpen : styles.buttonWrapperClosed}
      onPress={() => {
        if (open) { return; }
        else {
          reset();
          setOpen(true);
        }
      }}
    >
      {open ?
        <TouchableOpacity
          activeOpacity={1}
          onPress={Keyboard.dismiss}
        >
          <View style={{ display: 'flex', flexDirection: 'row', justifyContent: 'space-between', paddingTop: 5, paddingBottom: 5 }}>
            <Text style={{ left: 5, fontSize: 16 }}>Add {page === 'lists' ? 'list' : 'item'}</Text>
            <TouchableOpacity
              activeOpacity={1}
              onPress={() => {
                reset();
                Keyboard.dismiss();
                setOpen(false);
              }}
            >
              <Entypo name="chevron-thin-down" size={24} color="black" style={{ right: 5, fontSize: 20 }} />
            </TouchableOpacity>
          </View>
          <View style={styles.openForm}>
            {(errors.amount?.type || errors.name?.type) === 'required' && <Text style={styles.errorText}>
              Please fill in all the fields.
            </Text>}
            {(errors.amount?.type || errors.name?.type) === 'pattern' && <Text style={styles.errorText}>
              Only valid characters allowed. ({errors.amount && `Amount${errors.name ? ', ' : ''}`}{errors.name && 'Name'})
            </Text>}
            <Controller
              name='name'
              control={control}
              rules={{
                minLength: 1,
                maxLength: 17,
                required: true,
                pattern: /^[\w_-]+$/,
              }}
              render={({ field: { onChange, onBlur, value } }) => {
                return (
                  <View style={styles.formWrapper}>
                    <Text style={styles.formText}>Name: </Text>
                    <TextInput
                      placeholder={page === 'lists' ? 'List name' : 'Bread'}
                      onBlur={onBlur}
                      onChangeText={onChange}
                      value={value}
                      style={styles.formInput}
                      maxLength={17}
                      returnKeyType={page === 'lists' ? 'done' : 'next'}
                      onSubmitEditing={() => {
                        if (page === 'lists') {
                          Keyboard.dismiss();
                          return;
                        }
                        amountRef.current.focus();
                      }}
                    />
                  </View>
                );
              }}
            />
            {page !== 'lists' &&
              <Controller
                name='amount'
                control={control}
                rules={{
                  minLength: 1,
                  maxLength: 5,
                  required: true,
                  pattern: /^[\d]+$/,
                }}
                render={({ field: { onChange, onBlur, value } }) => {
                  return (
                    <View style={styles.formWrapper}>
                      <Text style={styles.formText}>Amount: </Text>
                      <TextInput
                        placeholder={'1'}
                        onBlur={onBlur}
                        onChangeText={onChange}
                        value={value}
                        style={[styles.formInput, { width: 50 }]}
                        maxLength={5}
                        ref={amountRef}
                        keyboardType='number-pad'
                        returnKeyType='done'
                        onSubmitEditing={Keyboard.dismiss}
                      />
                    </View>
                  );
                }}
              />
            }
            <TouchableOpacity
              activeOpacity={0.8}
              style={styles.button}
              onPress={onSubmit}
            >
              <Text>Add to list</Text>
            </TouchableOpacity>
          </View>
        </TouchableOpacity>
        :
        <View>
          <MaterialIcons name="playlist-add" size={50} color="#000000" />
          <MaterialIcons name="playlist-add" size={50} color="#00000040" style={{ position: 'absolute', left: 2, top: 2 }} />
        </View>
      }
    </TouchableOpacity>
  );
};
